Repository AppQuality/unguess-design-system, pull requests merged in 2022-03, with the labels that each got.

#1 Cup 422 setup theme
  .gitignore
  .prettierrc
  .storybook/preview-head.html
  .storybook/preview.js
  package.json
  src/index.tsx
  src/stories/button/index.stories.tsx
  src/stories/button/index.tsx
  src/stories/shared/globalStyle.ts
  src/stories/theme/index.ts
  yarn.lock
Labels: minor

#2 Cup 427 ds buttons
  .storybook/main.js
  generate-story.sh
  package.json
  src/index.tsx
  src/react-app-env.d.ts
  src/stories/breadcrumbs/_types.tsx
  src/stories/breadcrumbs/index.stories.tsx
  src/stories/breadcrumbs/index.tsx
  src/stories/button/index.stories.tsx
  src/stories/button/index.tsx
  src/stories/buttons/anchor/_types.tsx
  src/stories/buttons/anchor/index.stories.tsx
  src/stories/buttons/anchor/index.tsx
  src/stories/buttons/button-group/_types.tsx
  src/stories/buttons/button-group/index.stories.tsx
  src/stories/buttons/button-group/index.tsx
  src/stories/buttons/button/_types.tsx
  src/stories/buttons/button/index.stories.tsx
  src/stories/buttons/button/index.tsx
  src/stories/buttons/icon-button/_types.tsx
  src/stories/buttons/icon-button/index.stories.tsx
  src/stories/buttons/icon-button/index.tsx
  src/stories/buttons/shared/_shared.tsx
  src/stories/buttons/split-button/_types.tsx
  src/stories/buttons/split-button/index.stories.tsx
  src/stories/buttons/split-button/index.tsx
  src/stories/buttons/utils/useButtonVariant.ts
  src/stories/theme/index.ts
  yarn.lock
Labels: major

#3 Typography components
  package.json
  src/index.tsx
  src/stories/buttons/anchor/index.stories.tsx
  src/stories/buttons/button/index.stories.tsx
  src/stories/typography/block-quote/_types.tsx
  src/stories/typography/block-quote/index.stories.tsx
  src/stories/typography/block-quote/index.tsx
  src/stories/typography/code/_types.tsx
  src/stories/typography/code/index.stories.tsx
  src/stories/typography/code/index.tsx
  src/stories/typography/ellipsis/_types.tsx
  src/stories/typography/ellipsis/index.stories.tsx
  src/stories/typography/ellipsis/index.tsx
  src/stories/typography/lists/_types.tsx
  src/stories/typography/lists/index.tsx
  src/stories/typography/lists/ordered.stories.tsx
  src/stories/typography/lists/unordered.stories.tsx
  src/stories/typography/paragraph/_types.tsx
  src/stories/typography/paragraph/index.tsx
  src/stories/typography/paragraph/ordered.stories.tsx
  src/stories/typography/typescale/_types.tsx
  src/stories/typography/typescale/index.stories.tsx
  src/stories/typography/typescale/index.tsx
  yarn.lock
Labels: minor

#4 Cup 424 accordion
  README.md
  package.json
  src/stories/accordion/_types.tsx
  src/stories/accordion/index.stories.tsx
  src/stories/accordion/index.tsx
  src/stories/breadcrumbs/_types.tsx
  src/stories/breadcrumbs/index.stories.tsx
  src/stories/breadcrumbs/index.tsx
  src/stories/grid/col/_types.tsx
  src/stories/grid/col/index.stories.tsx
  src/stories/grid/col/index.tsx
  src/stories/grid/grid/_types.tsx
  src/stories/grid/grid/index.stories.tsx
  src/stories/grid/grid/index.tsx
  src/stories/grid/row/_types.tsx
  src/stories/grid/row/index.stories.tsx
  src/stories/grid/row/index.tsx
  yarn.lock
Labels: minor

#5 add avatar component
  package.json
  src/stories/avatar/_types.tsx
  src/stories/avatar/index.stories.tsx
  src/stories/avatar/index.tsx
  yarn.lock
Labels: good first issue, minor

#6 Cup 446 wells
  package.json
  src/stories/accordions/_types.tsx
  src/stories/accordions/index.stories.tsx
  src/stories/accordions/index.tsx
  src/stories/cards/_types.tsx
  src/stories/cards/index.stories.tsx
  src/stories/cards/index.tsx
  yarn.lock
Labels: minor

#15 Login form
  src/index.tsx
  src/stories/item/_types.tsx
  src/stories/item/index.tsx
  src/stories/login-form/_types.tsx
  src/stories/login-form/index.stories.tsx
  src/stories/login-form/index.tsx
  src/stories/menu/_types.tsx
  src/stories/menu/index.tsx
Labels: minor

#17 add logo component + fix login-form component issues
  src/assets/logo-horizontal.svg
  src/assets/logo-icon.svg
  src/assets/logo-vertical.svg
  src/assets/logo.svg
  src/stories/login-form/_types.tsx
  src/stories/login-form/index.stories.tsx
  src/stories/login-form/index.tsx
  src/stories/logo/_types.tsx
  src/stories/logo/index.stories.tsx
  src/stories/logo/index.tsx
Labels: minor

#23 refactor(icons): move used icon inside prj assets folder and remove @zendesk/svg-icons as dep
  package.json
  src/assets/icons/chevron-down-stroke.svg
  src/assets/icons/chevron-left-stroke.svg
  src/assets/icons/chevron-right-stroke.svg
  src/assets/icons/file-image-stroke.svg
  src/assets/icons/file-presentation-stroke.svg
  src/assets/icons/home-fill-styled.svg
  src/assets/icons/home-fill.svg
  src/assets/icons/leaf-stroke.svg
  src/assets/icons/megaphone-stroke.svg
  src/assets/icons/menu-stroke.svg
  src/assets/icons/token.svg
  src/assets/icons/user-solo-stroke.svg
  src/stories/avatar/index.stories.tsx
  src/stories/buttons/button/index.stories.tsx
  src/stories/buttons/icon-button/index.stories.tsx
  src/stories/buttons/split-button/index.stories.tsx
  src/stories/intro.stories.mdx
  src/stories/login-form/index.stories.tsx
  src/stories/login-form/index.tsx
  src/stories/navigation/app-header/_types.tsx
  src/stories/navigation/app-header/index.tsx
  src/stories/navigation/header/header-item/brandItem.tsx
  src/stories/navigation/nav/nav-item/_types.tsx
  src/stories/navigation/nav/nav-item/navToggle.tsx
  src/stories/navigation/sidebar/index.tsx
  src/stories/tags/index.stories.tsx
  src/stories/tiles/index.stories.tsx
  yarn.lock
Labels: patch

#24 build(components): add component to index
  src/index.tsx
  src/stories/modal/_types.tsx
  src/stories/modal/index.stories.tsx
  src/stories/modal/index.tsx
  src/stories/modals/_types.tsx
  src/stories/modals/index.stories.tsx
  src/stories/modals/index.tsx
  src/stories/navigation/nav/nav-item/index.ts
  src/stories/navigation/sidebar/index.tsx
Labels: minor

#27 Feature/cup 500 campaign card
  src/assets/icons/arrival-status-round-icon.svg
  src/assets/icons/completed-status-round-icon.svg
  src/assets/icons/functional-test-round-icon.svg
  src/assets/icons/on-going-status-round-icon.svg
  src/assets/icons/regression-test-round-icon.svg
  src/index.tsx
  src/stories/campaignCards/_types.tsx
  src/stories/campaignCards/index.stories.tsx
  src/stories/campaignCards/index.tsx
  src/stories/theme/index.ts
Labels: minor
